### ISSUE TITLE
How can I get the starfys/tcpdump_controller?

### ISSUE THREAD

**Issue by TrumenBI** [starfys/packet_captor_sakura#1]
Hi, I was tried to run your code on a Ubuntu OS with VMware, but I can't find starfys/tcpdump_controller on hub.docker.com or use docker search command. Was the starfys/tcpdump_controller become private or something?
If so, could you please tell me where can I get a substitute? I'm new to this. :(

**Comment by starfys** [comment]
Try
```
cd data_collection/tcpdump_controller
make
```
AFAIK, running `make` in `data_collection` should do this automatically though

**Comment by TrumenBI** [comment]
Thanks！
It worked！
